[package]
name = "protocol-core"
version = "0.1.0"
edition = "2021"

[dependencies]
lazy_static = "1.5.0"
tokio = { version = "1.38.0", features = ["full"] }

protocol-buf = { path = "../protocol-buf" }
protocol-packets = { path = "../protocol-packets" }
